//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portable_BMU_App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<Matrix4x4 xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <M11>0</M11>
  <M12>0</M12>
  <M13>0</M13>
  <M14>0</M14>
  <M21>0</M21>
  <M22>0</M22>
  <M23>0</M23>
  <M24>0</M24>
  <M31>0</M31>
  <M32>0</M32>
  <M33>0</M33>
  <M34>0</M34>
  <M41>0</M41>
  <M42>0</M42>
  <M43>0</M43>
  <M44>0</M44>
  <Translation>
    <X>0</X>
    <Y>0</Y>
    <Z>0</Z>
  </Translation>
</Matrix4x4>")]
        public global::System.Numerics.Matrix4x4 CalibrationMatrix {
            get {
                return ((global::System.Numerics.Matrix4x4)(this["CalibrationMatrix"]));
            }
            set {
                this["CalibrationMatrix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int boxHeight {
            get {
                return ((int)(this["boxHeight"]));
            }
            set {
                this["boxHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<Vector3 xmlns:xsi=\"http://www.w3.org/20" +
            "01/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <X>0</X>" +
            "\r\n  <Y>0</Y>\r\n  <Z>0</Z>\r\n</Vector3>")]
        public global::System.Numerics.Vector3 boxOrg {
            get {
                return ((global::System.Numerics.Vector3)(this["boxOrg"]));
            }
            set {
                this["boxOrg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int boxWidth {
            get {
                return ((int)(this["boxWidth"]));
            }
            set {
                this["boxWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int boxDepth {
            get {
                return ((int)(this["boxDepth"]));
            }
            set {
                this["boxDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCalibration {
            get {
                return ((bool)(this["isCalibration"]));
            }
            set {
                this["isCalibration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gpsConfigFilePath {
            get {
                return ((string)(this["gpsConfigFilePath"]));
            }
            set {
                this["gpsConfigFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standing Position")]
        public string ScanPosition {
            get {
                return ((string)(this["ScanPosition"]));
            }
            set {
                this["ScanPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedRootPath {
            get {
                return ((string)(this["SavedRootPath"]));
            }
            set {
                this["SavedRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public UnitInterFaceV733.ChooseScannerType ScannerType {
            get {
                return ((UnitInterFaceV733.ChooseScannerType)(this["ScannerType"]));
            }
            set {
                this["ScannerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Lateral {
            get {
                return ((float)(this["Lateral"]));
            }
            set {
                this["Lateral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataFolder {
            get {
                return ((string)(this["DataFolder"]));
            }
            set {
                this["DataFolder"] = value;
            }
        }
    }
}
